apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry: {limit: 10, backoff: {duration: 10s, factor: 2, maxDuration: 3m}}
    syncOptions: [CreateNamespace=true]
  source:
    repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
    targetRevision: main
    path: manifests/argo
