apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry: {limit: 10, backoff: {duration: 10s, factor: 2, maxDuration: 3m}}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 2.0.11
      helm:
        releaseName: argo-workflows
        valueFiles: [$values/values/argo-workflows.yaml]
    - repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
      targetRevision: main
      ref: values
