apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
    targetRevision: main
    path: manifests/infisical-config
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry: {limit: 10, backoff: {duration: 10s, factor: 2, maxDuration: 3m}}
