apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turnstone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: turnstone
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry: {limit: 10, backoff: {duration: 10s, factor: 2, maxDuration: 3m}}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  sources:
    - repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
      targetRevision: main
      path: charts/turnstone
      helm:
        releaseName: turnstone
        valueFiles: [$values/values/turnstone.yaml]
    - repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
      targetRevision: main
      path: manifests/turnstone
    - repoURL: https://github.com/thomashenselqvest/sldcbackendtest.git
      targetRevision: main
      ref: values
